name: main

on:
  schedule:
    - cron: '30 10 29 * *'
  push:
    branches:
      - main

jobs:
  saft:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - run: |
        go run cmd/saft_request/main.go
      env: 
        EMAIL_API_KEY=${{ secrets.EMAIL_API_KEY }}
        EMAIL_CONTENT=${{ secrets.EMAIL_CONTENT }}
        EMAIL_FROM_NAME=${{ secrets.EMAIL_FROM_NAME }}
        EMAIL_FROM=${{ secrets.EMAIL_FROM }}
        EMAIL_TO_NAME=${{ secrets.EMAIL_TO_NAME }}
        EMAIL_TO=${{ secrets.EMAIL_TO }}
        EMAIL_SUBJECT=${{ secrets.EMAIL_SUBJECT }}
        ACCOUNT_NAME=${{ secrets.ACCOUNT_NAME }}
        API_KEY=${{ secrets.API_KEY }}
